<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rasad.Application\Rasad.Application.csproj" />
    <ProjectReference Include="..\Rasad.Domain\Rasad.Domain.csproj" />
  </ItemGroup>
</Project>
